---
title: "227.215 Biostats Lab 4"
author: "Jonathan Marshall"
date: "30 August 2016"
output:
  pdf_document: null
  html_document: default
graphics: yes
---

## Introduction ##

In this lab we'll return to the set of data on the birth weight of lambs, based on the data from last year's project, and assess whether there might be a differential effect of shearing or feed treatment dependent on whether the lamb is a single or twin. This will therefore be good practice for the last part of your project this year.

After that, we'll look at a set of data on plate meter measurements of grass, and how we can treat the lack of independence of residuals through the use of random effects.

## Exercise 1: Load up your R script 

1. Load up your RStudio project from last time and load in your R script.

2. Take the opportunity to go through your script and recall what we did last time around. You can re-execute any lines as needed to help remember what they do.

3. Add comments to your script if you've forgotten anything.

4. Compile your notebook and make sure the title and author etc. have been correctly set in the HTML or Word document.

## Exercise 2: Assessing for a differential effect of shearing and feed treatment on twins.

1. Create a new linear model, adding an **interaction** term to your model between `Shorn` and `Rank`. Remember that you can do this by adding `Shorn:Rank` to your model, i.e.

    ```
    mod_rank <- lm(BirthWeight ~ Sex + Rank + Feed + Shorn + Shorn:Rank, data=births)
    ```

2. Use the `anova` function to assess whether the interaction term is significant or not.

3. Is there evidence for a differential effect of shearing on twins compared with singles? Add some notes about this to your R script.

4. Take a look at the `summary` table for the model. What does the `RankTwin:ShornYes` coefficient represent?

5. Add the following code which looks at the effect of shearing broken up by rank.

    ```
    plot(BirthWeight ~ interaction(Shorn, Rank), data=births)
    ```

    Does this plot agree with your anova results?
   
6. Try visualising your model fit using `visreg`. We're interested in visualising the effect of the shearing treatment by rank. We can do this using

    ```
    library(visreg)
    visreg(mod_rank, "Shorn", by="Rank")
    ```

    This should produce side by side plots of the model fit - compare these to the boxplots you did above.

7.  You can also show them on the same plot by adding `overlay=TRUE` into the `visreg` command. Try this to see what you get. Compare your plots with
the output in the summary table. They're be telling you the same thing!

8.  Repeat the above, this time adding an interaction term between `Feed` and `Rank`. Is there evidence of a differential effect of feed between twins and singles?

## Exercise 3: Create a new R script

In this exercise we'll look at some grass measurement data collected by Animal Production students in 2013 using grass plate meters.

1. Create a new R script file, and copy and paste the metadata block from your lab3.R script into it, changing the title.

2. Add the following lines to read in the grass measurement data and take a look at the summary.

    ```
    #' Read in data on grass measurements
    grass <- read.csv("http://www.massey.ac.nz/~jcmarsha/227215/data/grass.csv")
    summary(grass)
    ```

3. Add some code and comments to your R script to produce some plots of `metread` versus the covariates `farm`, `paddock`, and `person`.

4. Is there any graphical evidence that the plate meter readings changes between farms, paddocks or the person using the meter? Add some comments to your R script.

5. Build a linear model to assess whether the plate meter readings differ by farm. What is your conclusion? Add some comments to your R script.

6. Now built a linear model incorporating `person` as well as `farm`. What is your conclusion now about whether plate meter readings differ by farm?

7. Compare your results from 5 and 6, and add some comments to your R script as to why they differ.

## Exercise 4: Incorporating a random effect for person

The problem with our linear model from part 6 is that by including the person in the model, we can no longer predict what the average measurement will be on those farms should **other** people take them. Our model is restricted to just the people that did the initial measures.

Ideally, we'd want to account for the variation between people while not having to include it in the model for prediction.

We can do this by treating the person variable as **random**. The basic idea is that we have multiple residuals for each person, so the average of the residuals for a particular person could be treated as that persons effect on the measurement.  We basically rewrite the residuals as

$$
\epsilon_{ij} = \mathsf{person}_i + \eta_{ij}
$$

where $\epsilon_{ij}$ is the $j$-th residual of person $i$ from the linear model with just farm in it, $\mathsf{person}_i$ is the average residual for person $i$, and $\eta_{ij}$ is the left-over $j$-th after subtracting out the person level average.

We do this in such a way that the mean of the person effects is 0. Thus, to predict for a new person, we just set the person effect to 0 and incorporate the variation in the person effects into prediction intervals.

To do this in R, we use the `nlme` library, which stands for "non-linear mixed effects". The mixed is because we're mixing normal linear model coefficients (fixed effects) with random effects.

1. Start by loading the library in and fitting a model

    ```
    #' Load in the nlme library
    library(nlme)
    #' Fit a model incorporating a random effect for person
    mixed <- lme(metread ~ farm, random=~1|person, data=grass)
    ```

    The `random` bit here can be read as specifying separate mean (intercept) for each person.

2. Do an anova and summary table for the mixed model. What is your conclusion?

3. Notice that the summary table gives you some information about your random effects. The `Intercept` value is the standard deviation of the per-person random effect (i.e. between-person variability), while the `Residual` value is the standard deviation of the left-over residuals after accounting for people (i.e. the within-person variability). You should notice that there is more within-person variation than there is between-person variation.

4. Summarise your results in a few comments in your R script file.

5. All the best for the rest of the course! I'd love to get feedback from you on the biostats portion of the course - feel free to tell me what you think via email or an anonymous note under my door! It'd be great to get a representative sample of responses, so it's important that I get the *meh* responses as well as the *awesome* and *you suck* responses! :)