---
title: "227.215 Biostats Lab 2"
author: "Jonathan Marshall"
date: "25 July 2016"
output:
  pdf_document: null
  html_document: default
graphics: yes
---

## Introduction ##

In this lab we'll cover multiple linear regression, using the data on Moroccan donkeys. We'll also look at visualising model fit.

## Exercise 1: Reload your R project and script ##

1. Start by reloading your R script from last week. If you don't have it, you can grab a copy of Jonathan's version `donkey.R` from stream (under sol1 in the Computer Labs folder) and place a copy in your documents folder, then load that into R.

2. If you haven't already done so, now would be a good time to go through the script from last week and **add some comments** so you remember what each line of R code is doing, and what your conclusions are about the output.

## Exercise 2: Multiple regression ##

In this exercise, we'll extend our linear model to take into account some of the other variables in the data.

1. We'll start by adding in the umbilical girth to the first model (`lm1`). You can do that as follows.

    ```{r, eval=FALSE}
    #' A linear model containing both heart and umbilical girths.
    lm3 <- lm(Bodywt ~ Heartgirth + Umbgirth, data=donkey)
    ```
2. Produce the model summary of this, and compare it to the model summary of `lm1`. You'll notice a few things.
    * The estimate for `Heartgirth` will have changed.
    * There is a new row for `Umbgirth`.

3. Why do you think the estimate (and thus P-values etc) for `Heartgirth` changed?  What is the P-value here testing? *add some notes to your R-script about this*.

4. What is your conclusion about the relationship between `Bodywt`, `Heartgirth` and `Umbgirth`?

5. Now add in both `Length` and `Height` to your linear model, and check the model summary. What is your conclusion about the relationship between `Bodywt` and `Height` ?

6. Do a linear model relating `Bodywt` to only `Height`. You should find that `Height` is highly significant. Why is it not significant in the larger model?

7. Try removing `Height` and adding `Sex` into your model. Recall that it didn't look as if there was an effect of sex when we saw the boxplot, or when we looked at a linear model containing just `Sex` in lectures. What is your conclusion now? Why would this be?

8. Take a look at visualising your model with all four variables using `visreg`. You'll notice that it will produce 4 plots, one for each of the variables. You can see them all at once by adding `par(mfrow=c(2,2), mar=c(4,4,2,2))` before your `visreg` command.

    These are called **partial** residual plots. What they do is plot the relationship between the response and a single variable after holding all other variables constant (usually at their median). This allows you to see the effect of one variable after accounting for the others. Notice the relationship with `Height` isn't very strong. You can choose a particular variable by using the `xvar` variable. e.g. `visreg(lm4, xvar="Length")`.

9. Take a look at the model diagnostics for the model with all covariates. Look at all 4 plots using `plot(lm4)` after first running the `par` line from part 8. *Add some notes to your R script as to whether the model assumptions are satisfied*.

10. Re-build your Word document and make sure it includes everything you want it to. You'll be wanting to refer back to it later.

## Exercise 3

In this exercise we'll look at the Petrels dataset from semester 1. Recall that last semester we found that there was an effect of sex on right wing lengths, with male birds generally being larger, and also there was an effect of area, with those in area 5 in particular being larger.

**A question we couldn't answer last semester was whether the area effect we saw last semester was genuine, or whether it could just be due to more males in Area 5 compared to other areas.**

1. Start by creating a new R script, and reading the data in. You can find the data at

    ```
    http://www.massey.ac.nz/~jcmarsha/227215/data/petrels.csv
    ```

2. Remember to convert the `Area` variable to a factor.

3. Remind yourself as to how many birds were in each area by producing a table of `Sex` vs `Area`. Remember that `table(data$col1, data$col2)` can be used for this, where `data` is the name of your dataset, and `col1` and `col2` are the column names you wish to tabulate.

4. Remind yourself what the differences were in areas and in sex by doing plots of the right wing length versus sex and area.

5. Produce a linear model for right wing length using `Sex` as a covariate. Take a look at the summary output. What is your conclusion?

6. Now produce a linear model for right wing length using `Area` as a covariate. Recall that the overall P-value can be used to assess whether *any* of your covariates (in this case, just the area effect) is important or not. What is your conclusion?

6. Next produce a linear model with both `Sex` and `Area` in it. What is your conclusion from this model? Which area has the largest and smallest wing lengths after accounting for sex?

7. Try visualising your model using `visreg`. Check that the results make sense. You might want to compare your results from the model containing both Sex and Area with the one containing just Area - how has including Sex in the model altered the results?

8. Take a look at the model diagnostics. Are the model assumptions satisifed?
