---
title: "227.215 Biostats Lab 3"
author: "Jonathan Marshall"
date: "15 August 2016"
output:
  pdf_document: null
  html_document: default
graphics: yes
---

## Introduction ##

In this lab we'll look at a set of data on the birth weight of lambs, based on the data from a previous year's project. This will therefore be good practice for your project this year!

Lamb birth weight is the single largest influence on survival of lambs in the first few days of life.  In this lab we'll be looking at a dataset on the birth weight of lambs collected during a trial at Massey in the late 1990s.

Mixed-aged, Border Leicester x Romney ($n=160$) ewes were randomly allocated after preganancy diagnosis to a factorial experiment involving two shearing treatments (shorn on day 70 vs not); two pregnancy ranks (single or twin); and four feeding regimes (HH, HM, MH, MM), where the first letter refers to feed during days 70-101 of pregancy, and the second during days 102-140.  The M (maintenance) feeding group were fed at a level calculated to maintain maternal conceptus-free weight, while the H (high) feeding group were fed to gain around 100g per day above this during the relevant period.

Of particular interest is how feed management and shearing during pregnancy influence lamb birth weight.  The data set consists of the following variables from 204 lambs.

Variable      Description
--------      -----------
`DamID`       Identifying number for the ewe.
`LambID`      Identifying number for the lamb.
`DateBirth`   Date of birth of the lamb.
`Rank`        Whether the lamb was Single or a Twin.
`Sex`         The sex of the lamb (Male, Female).
`BirthWeight` The weight of the lamb at birth (in kg).
`Feed`        The feed regime of the ewe (HH, HM, MH, HH).
`Shorn`       Whether the ewe was shorn during pregnancy (Yes, No).

## Exercise 1: Create a new R script file

1. You can create a new RStudio project for this lab if you like (or use a previous one - up to you).

2. Create a new R script for todays lab.

3. Remember that you can add a special 'metadata' block to the top of the script that allows you to set the title and author. Copy and paste the following code block, then change the author as appropriate. There's a bunch of other stuff you can do to format up R notebooks (e.g. headings, subheadings, bullet points, emphasis etc.) that can be found in the summary sheet on stream.

    ```
    #' ---
    #' title:  227.215 Biostats, Lamb birthweight analysis
    #' author: Joanne Blogs
    #' date:   16 August 2016
    #' ---
    ```
    
4. Add the following code to read the dataset in and take a look at the first few rows.

    ```
    #' Read in the lamb birthweight data
    births <- read.csv("http://www.massey.ac.nz/~jcmarsha/227215/data/birthweight.csv")
    head(births)
    ```

5. Compile your notebook and make sure the title and author etc. have been correctly set in the HTML or Word document.

## Exercise 2: Was the experiment balanced?

The goal of this exercise is to see if there were similar numbers of ewes in each treatment group.

1. Take a look at the data. You should notice that each row represents a lamb rather than a ewe, thus any ewe with twins will have more than one row associated with it.

2. Start by writing some code to pick out just the columns that are ewe-specific. i.e. you'll want `DamID`, `Feed` and `Shorn`. You can do this by choosing the columns by number using the square bracket notation, or by name, e.g. to pick out the 1st and 2nd columns you can use `births[, c(1,2)]` or `births[,c("DamID", "LambID")]`. You'll want to make sure you save the result by assigning it to a new variable name, say `ewe_cols`.

3. Now that we have that, we can use the `unique` command on the `ewe_cols` data frame to produce a data frame with just the unique rows. As the `DamID` is included, this will give us one row per ewe (assuming each ewe was allocated to a single feed and shearing treatment!) Make sure you save the result of that, e.g. you could call it `ewes`.

4. Using the `ewes` data frame, produce a table of the number of ewes in each feed treatment by the shearing treatment. Remember you can use the `table` command for tables.

5. Make sure you add some hashquotes to your R script describing what is being done - you'll find it useful to be able to come back to this later!

## Exercise 3: Exploratory analysis of birthweight data

For this and the remaining exercises, we'll be using the original data `births`.

1. Add some code and comments to your R script to produce some plots of `BirthWeight` versus the covariates `Rank`, `Sex`, `Feed` and `Shorn`.

2. Is there any graphical evidence for a relationship between `BirthWeight` and these variables?

3. What does the distribution of `BirthWeight` look like within each of the categories? Do you think the linear model assumptions will hold for these data?

## Exercise 4: Linear modelling of birthweight data

In this exercise we'll look at analysing the average birthweight with a linear model. **Remember to add comments to your R script so that when you compile the notebook you have some commentary to look back on later.**

1. Fit a linear model to the data using only the `Shorn` variable.

    a. What is the linear model equation?
    
    b. Produce an ANOVA table and model summary table.
    
    c. Is the ewe being shorn important for birthweight according to this model?

2. Fit a linear model to the data using only the `Feed` variable.

    a. How has `Feed` been incorporated into the linear model?
    
    b. Produce an ANOVA table and model summary table.
    
    c. Is the ewes feeding treatment important for birthweight according to this model?

3. Fit a multivariable linear model using the four covariates `Sex`, `Rank`, `Feed` and `Shorn`.

    a. Produce an ANOVA table and model summary table.
    
    b. Which variables (if any) are important for birth weight?
    
    c. Interpret the summary table coefficients and write some comments into your R script about this.
    
    d. Are your results consistent with part 1 and 2? If not, why not?
    
    e. Produce a prediction, with 95% interval, for the weight of a male twin, born to an unshorn ewe on the HM feeding treatment.
    
    f. Produce a prediction, with 95% interval, for the average weight of a female singles, born to an unshorn ewes on the MM feeding treatment.
    
    g. Load the `visreg` package using `library(visreg)`, and run `visreg` on the model. You'll notice you get four plots, one for each of the variables. You might like to use `par(mfrow=c(2,2))` to get a 2x2 plot before doing this.

    h. Finally, take a look at the model diagnostics for the model. Do the linear model assumptions seem to hold?
